# Adapted from https://medium.com/@bianca_ionescu99/run-jenkins-in-docker-container-for-c-c-projects-652dfa924a

services:
  jenkins-agent:
    container_name: Jenkins-Agent
    build:
      context: .
      dockerfile: Dockerfile
    privileged: true
    expose:
      - '22'
    networks:
      - jenkins-network
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=${SSH_AGENT_PUB_KEY}
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s

networks:
  jenkins-network:
    name: jenkins_network
    external: true